from flask import Blueprint, render_template, request, redirect, url_for, flash
from database.database import db
from models.project import Project
from models.risk import Risk, RiskHistory
from services.risk_engine import analyze_project
from services.prediction_engine import predict_project_risk, get_model_status
from services.analytics_engine import calculate_health_scores, generate_warnings

risks_bp = Blueprint("risks", __name__)


@risks_bp.route("/risk-analysis")
def risk_analysis():
    projects = Project.query.all()
    project_id = request.args.get("project_id", type=int)
    selected = None
    risks = []
    warnings = []
    if projects:
        selected = Project.query.get(project_id) if project_id else projects[0]
        risks = Risk.query.filter_by(project_id=selected.id).order_by(Risk.risk_score.desc()).all()
        warnings = generate_warnings(selected)
    return render_template("risk_analysis.html", projects=projects, selected=selected,
                            risks=risks, warnings=warnings)


@risks_bp.route("/risk-analysis/<int:project_id>/rerun", methods=["POST"])
def rerun_analysis(project_id):
    project = Project.query.get_or_404(project_id)
    # Resolve old active risks generated by the rule engine before regenerating
    Risk.query.filter_by(project_id=project.id, source="rule-engine", status="Active").update(
        {"status": "Resolved"}
    )
    new_risks = analyze_project(project)
    for r in new_risks:
        db.session.add(r)
    db.session.commit()

    health = calculate_health_scores(project)
    db.session.add(RiskHistory(project_id=project.id, risk_score=health["overall_risk_score"],
                                health_score=health["overall_health"]))
    db.session.commit()
    flash("Risk analysis re-run successfully.", "success")
    return redirect(url_for("risks.risk_analysis", project_id=project.id))


@risks_bp.route("/predictions")
def predictions():
    projects = Project.query.all()
    project_id = request.args.get("project_id", type=int)
    selected = None
    prediction = None
    if projects:
        selected = Project.query.get(project_id) if project_id else projects[0]
        prediction = predict_project_risk(selected)
    model_status = get_model_status()
    return render_template("risk_analysis.html", projects=projects, selected=selected,
                            risks=Risk.query.filter_by(project_id=selected.id).all() if selected else [],
                            warnings=generate_warnings(selected) if selected else [],
                            prediction=prediction, model_status=model_status, is_predictions_page=True)
